/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ManegerService } from "../maneger.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ManegerCreateInput } from "./ManegerCreateInput";
import { ManegerWhereInput } from "./ManegerWhereInput";
import { ManegerWhereUniqueInput } from "./ManegerWhereUniqueInput";
import { ManegerFindManyArgs } from "./ManegerFindManyArgs";
import { ManegerUpdateInput } from "./ManegerUpdateInput";
import { Maneger } from "./Maneger";
import { EmployFindManyArgs } from "../../employ/base/EmployFindManyArgs";
import { Employ } from "../../employ/base/Employ";
import { EmployWhereUniqueInput } from "../../employ/base/EmployWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ManegerControllerBase {
  constructor(
    protected readonly service: ManegerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Maneger })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ManegerCreateInput): Promise<Maneger> {
    return await this.service.create({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Maneger] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ManegerFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Maneger[]> {
    const args = plainToClass(ManegerFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Maneger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ManegerWhereUniqueInput
  ): Promise<Maneger | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Maneger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ManegerWhereUniqueInput,
    @common.Body() data: ManegerUpdateInput
  ): Promise<Maneger | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Maneger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ManegerWhereUniqueInput
  ): Promise<Maneger | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Employ",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/emploies")
  @ApiNestedQuery(EmployFindManyArgs)
  async findManyEmploies(
    @common.Req() request: Request,
    @common.Param() params: ManegerWhereUniqueInput
  ): Promise<Employ[]> {
    const query = plainToClass(EmployFindManyArgs, request.query);
    const results = await this.service.findEmploies(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        maneger: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/emploies")
  async connectEmploies(
    @common.Param() params: ManegerWhereUniqueInput,
    @common.Body() body: EmployWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emploies: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/emploies")
  async updateEmploies(
    @common.Param() params: ManegerWhereUniqueInput,
    @common.Body() body: EmployWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emploies: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Maneger",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/emploies")
  async disconnectEmploies(
    @common.Param() params: ManegerWhereUniqueInput,
    @common.Body() body: EmployWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emploies: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
