/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ManyService } from "../many.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ManyCreateInput } from "./ManyCreateInput";
import { ManyWhereInput } from "./ManyWhereInput";
import { ManyWhereUniqueInput } from "./ManyWhereUniqueInput";
import { ManyFindManyArgs } from "./ManyFindManyArgs";
import { ManyUpdateInput } from "./ManyUpdateInput";
import { Many } from "./Many";
import { OneFindManyArgs } from "../../one/base/OneFindManyArgs";
import { One } from "../../one/base/One";
import { OneWhereUniqueInput } from "../../one/base/OneWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ManyControllerBase {
  constructor(
    protected readonly service: ManyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Many })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ManyCreateInput): Promise<Many> {
    return await this.service.create({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Many] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ManyFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Many[]> {
    const args = plainToClass(ManyFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Many })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ManyWhereUniqueInput
  ): Promise<Many | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Many })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ManyWhereUniqueInput,
    @common.Body() data: ManyUpdateInput
  ): Promise<Many | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Many })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ManyWhereUniqueInput
  ): Promise<Many | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "One",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/ones")
  @ApiNestedQuery(OneFindManyArgs)
  async findManyOnes(
    @common.Req() request: Request,
    @common.Param() params: ManyWhereUniqueInput
  ): Promise<One[]> {
    const query = plainToClass(OneFindManyArgs, request.query);
    const results = await this.service.findOnes(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        manyes: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/ones")
  async connectOnes(
    @common.Param() params: ManyWhereUniqueInput,
    @common.Body() body: OneWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ones: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/ones")
  async updateOnes(
    @common.Param() params: ManyWhereUniqueInput,
    @common.Body() body: OneWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ones: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Many",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/ones")
  async disconnectOnes(
    @common.Param() params: ManyWhereUniqueInput,
    @common.Body() body: OneWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ones: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
